# Generated by Django 5.0.6 on 2024-08-13 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
