# Generated by Django 5.0.6 on 2024-09-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersitem',
            name='iscomplete',
            field=models.BooleanField(default=False),
        ),
    ]
