# Generated by Django 5.0.6 on 2024-09-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay_backend', '0003_ordersitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersitem',
            name='isstart',
            field=models.BooleanField(default=False),
        ),
    ]
