# Generated by Django 5.0.6 on 2024-09-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay_backend', '0004_ordersitem_isstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersitem',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
