# Generated by Django 5.0.6 on 2024-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.CharField(choices=[('Full Stack Development', 'Full Stack Development'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Data Science', 'Data Science'), ('Machine Learning', 'Machine Learning'), ('Cybersecurity', 'Cybersecurity'), ('Mobile App Development', 'Mobile App Development')], max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
