# Generated by Django 5.0.6 on 2024-08-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_file',
        ),
    ]
