# Generated by Django 5.0.6 on 2024-09-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_userprogress_delete_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
