# Generated by Django 5.0.6 on 2024-09-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userquizattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquizattempt',
            old_name='completed',
            new_name='passed',
        ),
        migrations.AddField(
            model_name='userquizattempt',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
