# Generated by Django 5.0.6 on 2024-09-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_completed_userquizattempt_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizattempt',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
