# Generated by Django 5.0.6 on 2024-09-19 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_userquizattempt_attempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquizattempt',
            old_name='attempt',
            new_name='attempts',
        ),
    ]
