# Generated by Django 5.0.6 on 2024-09-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_attempt_userquizattempt_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquizattempt',
            old_name='attempts',
            new_name='totalattempts',
        ),
    ]
